---
title: "Untitled"
author: "Church Army's Research Unit"
date: "Some-date"
output:
  word_document:
    reference_docx: caRefDoc.docx
---

```{r, include = FALSE, echo = FALSE}
#Five hashes is a fifth level heading, which is set to be a pagebreak in the reference document
#NB I think this template needs a little work
```


#Portsmouth Pioneer Project Evaluation Quantitative Report - Mock-up

## Pioneer Posts

At the beginning of the Pioneer Project, the ambition was to see 12 new fxC begun each with 50-100 worshippers and for 15% of the diocesan church attendance to be in fxC (from 1200 to 2200).

* fxC data from leaders and attenders surveys
* list of initiatives that didn't meet fxC criteria
* look at all fxC but focus in on any links with pioneer posts
* any fxC started by 'voluntar lay pioneers'

## Harbour Church
The original project plan aimed to “plant a large, city centre, resourcing church appealing to younger people. Within the 5 year timescales, we expect this to have grown to at least 200 worshippers and to be exploring a further plant”. 

This ambition was achieved within 18 months of Harbour Church’s planting  

## Pioneer Training & Vocations

* 'How to pioneer' course - numbers attending
* Recognised lay pioneers
* Pioneers accepted for reader and ordination training
* Who do the diocese consider to be pioneers (beyond the 'official' ones)?

## Culture Change
